name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pip
  - pip:
    - pandas
    - os
    - glob
    - ipywidgets
    - plotly.graph_objects
    - IPython.display
